name: build
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: ! startsWith(github.ref, 'refs/tags/')
      - uses: actions/setup-node@v1
        if: success()
        with:
          node-version: 8
          registry-url: 'https://npm.pkg.github.com'
          scope: '@gone-skiing'
      - run: npm ci
        if: success()
      - run: npm run check
        if: success()