name: build
on:
  push:
    tags-ignore:
      - 'v*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: 'https://npm.pkg.github.com'
          scope: '@gone-skiing'
      - run: npm ci
      - run: npm run check
