name: build
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v1

      - name: Setup
        if: success()
        uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: 'https://npm.pkg.github.com'
          scope: '@gone-skiing'

      - name: Install
        if: success()
        run: npm ci

      - name: Check
        if: success()
        run: npm run check
